---
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

dist: xenial

branches:
  only:
    - master

addons:
  apt:
    packages:
      - yamllint

before_script:
  - rustup component add rustfmt-preview

script:
  - yamllint .travis.yml
  - cargo fmt --all -- --check
  - cargo build
  - cargo run
