---
language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

dist: xenial

branches:
  only:
    - master

addons:
  apt:
    packages:
      - gperftools
      - yamllint

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - yamllint .travis.yml
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings
  - cargo build
  - cargo run
